# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/agent_imputter/',
                'doc_host': 'https://Islam-boussakaya.github.io',
                'git_url': 'https://github.com/Islam-boussakaya/agent_imputter',
                'lib_path': 'agent_imputter'},
  'syms': {'agent_imputter.core': {'agent_imputter.core.foo': ('core.html#foo', 'agent_imputter/core.py')}}}
