wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.14.2
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1681856598.198932
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 77
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 77
      3:
      - 2
      - 7
      - 19
      - 23
      4: 3.9.16
      5: 0.14.2
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: validation loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: training loss
      5: 1
      6:
      - 1
batch_size:
  desc: null
  value: 128
